import { test, expect } from '@playwright/test';

test('Baruproject', async ({ page }) => {
  await page.goto('https://staging.barucabinets.com/');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByLabel('Email Address*').click();
  await page.getByLabel('Email Address*').fill('heena.webosmotic@gmail.com');
  await page.getByLabel('Email Address*').press('Tab');
  await page.getByLabel('Password*').press('CapsLock');
  await page.getByLabel('Password*').fill('H');
  await page.getByLabel('Password*').press('CapsLock');
  await page.getByLabel('Password*').fill('');
  await page.getByLabel('Password*').press('CapsLock');
  await page.getByLabel('Password*').fill('H');
  await page.getByLabel('Password*').press('CapsLock');
  await page.getByLabel('Password*').fill('Heena@123*');
  await page.locator('form').getByRole('button', { name: 'Login' }).click();
  await page.locator('.MuiStack-root > div > .MuiBox-root > .MuiButtonBase-root').first().click();
  await page.getByRole('menuitem', { name: 'Add a New Project' }).click();
  await page.getByLabel('Project name').click();
  await page.getByLabel('Project name').fill('heenaproejct1112323');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('banner').getByRole('paragraph').click();
  await page.getByText('Browse cabinets').click();
  await page.locator('[id="\\:r25c\\:"]').click();
  await page.getByPlaceholder('Customer notes').click();
  await page.getByPlaceholder('Customer notes').fill('my notes');
  await page.getByRole('button', { name: 'ADD TO heenaproejct1112323' }).click();
  await page.getByRole('banner').getByRole('paragraph').click();
  await page.getByRole('button', { name: 'ADD TO SHOPPING CART' }).click();
  await page.getByRole('button', { name: '1', exact: true }).click();
  await page.getByRole('button', { name: 'CHECKOUT' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByPlaceholder('Job Name').click();
  await page.getByPlaceholder('Job Name').fill('heena my job');
  await page.getByPlaceholder('Notes').click();
  await page.getByPlaceholder('Notes').fill('this is my customer notes');
  await page.getByPlaceholder('Purchase Order').click();
  await page.getByPlaceholder('Purchase Order').fill('898989');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'PLACE ORDER' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Order Detail PDF' }).click();
  const download = await downloadPromise;
  await page.getByText('Thank you for your order, Heena!A member of our staff will be in touch with you').click();
  await page.getByRole('button', { name: 'My Orders' }).click();
  await page.getByRole('row', { name: 'heena my job 898989 20 Cooper' }).getByRole('button').first().click();
  await page.getByRole('tab', { name: 'Item' }).click();
  await page.getByRole('button').click();
  await page.getByRole('row', { name: 'heena my job 898989 20 Cooper' }).getByRole('button').nth(2).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Duplicate' }).click();
  await page.getByRole('banner').getByRole('paragraph').click();
});